### ISSUE TITLE
How do i generate a story with more than 1000 words?

### ISSUE THREAD

**Issue by hemanth2410** [pranavpsv/Genre-Based-Story-Generator#1]
Every time i generate a story with >1000 words it crashes and returns (Index out of range)

Setting `pad_token_id` to 50256 (first `eos_token_id`) to generate sequence
Traceback (most recent call last):
  File "D:\UnityProjects\SILVIA\Genre-Based-Story-Generator\idk.py", line 4, in <module>
    print(story_gen("<BOS> <action> Wattson",max_length=3000))
  File "C:\Users\saihe\AppData\Local\Programs\Python\Python36\lib\site-packages\transformers\pipelines.py", line 921, in __call__
    output_sequences = self.model.generate(input_ids=input_ids, **generate_kwargs)  # BS x SL
  File "C:\Users\saihe\AppData\Local\Programs\Python\Python36\lib\site-packages\torch\autograd\grad_mode.py", line 26, in decorate_context
    return func(*args, **kwargs)
  File "C:\Users\saihe\AppData\Local\Programs\Python\Python36\lib\site-packages\transformers\generation_utils.py", line 509, in generate
    model_kwargs=model_kwargs,
  File "C:\Users\saihe\AppData\Local\Programs\Python\Python36\lib\site-packages\transformers\generation_utils.py", line 547, in _generate_no_beam_search
    outputs = self(**model_inputs, return_dict=True)
  File "C:\Users\saihe\AppData\Local\Programs\Python\Python36\lib\site-packages\torch\nn\modules\module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "C:\Users\saihe\AppData\Local\Programs\Python\Python36\lib\site-packages\transformers\modeling_gpt2.py", line 778, in forward
    return_dict=return_dict,
  File "C:\Users\saihe\AppData\Local\Programs\Python\Python36\lib\site-packages\torch\nn\modules\module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "C:\Users\saihe\AppData\Local\Programs\Python\Python36\lib\site-packages\transformers\modeling_gpt2.py", line 609, in forward
    position_embeds = self.wpe(position_ids)
  File "C:\Users\saihe\AppData\Local\Programs\Python\Python36\lib\site-packages\torch\nn\modules\module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "C:\Users\saihe\AppData\Local\Programs\Python\Python36\lib\site-packages\torch\nn\modules\sparse.py", line 126, in forward
    self.norm_type, self.scale_grad_by_freq, self.sparse)
  File "C:\Users\saihe\AppData\Local\Programs\Python\Python36\lib\site-packages\torch\nn\functional.py", line 1852, in embedding
    return torch.embedding(weight, input, padding_idx, scale_grad_by_freq, sparse)
IndexError: index out of range in self

Here is the error

**Comment by pranavpsv** [comment]
The maximum-length that GPT2 can process/support is 1024 tokens. You can hack around this limit by first generating a story/text maximum of 1024 tokens, truncating the beginning part of that generated story/text and send the latter part of it as the prompt to continue generating more tokens and so on.

**Comment by hemanth2410** [comment]
Thanks, I will check it out.

**Comment by pranavpsv** [comment]
Closing this issue as the limitation has to do with the max length supported by GPT-2.
